security:
  oauth2:
    client:
      client-id: merryyou
      client-secret: merryyou
server:
  session:
    timeout: 60
  port: 9090
spring:
  session:
    store-type: redis
  redis:
    host: 10.194.80.12
    port: 6379
logging:
  level: debug
merryyou:
  security:
    oauth2:
      storeType: jwt
      jwtSigningKey: merryyou
      clients[0]:
        clientId: merryyou
        clientSecret: merryyou
      clients[1]:
              clientId: merryyou1
              clientSecret: merryyou1
